Dockerize to deploy with shinyproxy
mpascariu/MortalityCauses pull request #4
Opened 2021-12-18 15:48 UTC by doug-leasure

Added a `pkg_build.R` script that uses golem to create a Dockerfile.  

The dockerized app can be deployed using shinyproxy so that the app is more scalable because each user gets their own R environment.  This avoids the need for a Shiny Server Pro license. I successfully tested the app container with shinyproxy running behind nginx as a reverse proxy web server.

2021-12-19 12:34 UTC, mpascariu requested changes
Thanks @doug-leasure, docker is the way to go!
Not sure that we need to import {shinydashboard} package, do we? Apart from this the pr looks good to me.

2021-12-19 12:34 UTC, mpascariu commented on DESCRIPTION
> +  shinydashboard,
Probably we don't need to import {shinydashboard}, do we? 
We are dependent already on way to many libraries.

2021-12-20 10:12 UTC, doug-leasure commented
Hi @mpascariu, I think the `shinydashboard` dependency is coming from line 179 in `app_ui.R`.  The docker container returns an error from the app if shinydashboard is not included in the Imports.

2021-12-21 11:22 UTC, mpascariu commented
Ok. Let's leave it like this then, for now.

2021-12-21 11:22 UTC, merged